name: Release crate

run-name: "Release crate"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  publish-crate:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
